DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS password;
DROP TABLE IF EXISTS "user";
DROP SEQUENCE IF EXISTS postid;
DROP SEQUENCE IF EXISTS commentid;
